DROP TABLE IF EXISTS customers;

/;

CREATE TABLE customers (
   id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
   name VARCHAR (45),
   price DOUBLE,
   amount DOUBLE,
   author VARCHAR (90),
   isbn VARCHAR (45),
   genre VARCHAR (1),
   content_rate VARCHAR (2),
   PRIMARY KEY (ID)
);